version: '3.4'


# networks:
#   mynetwork:
#     driver: bridge
services:

  bancaapi:
    container_name: banca_api 
    image: ${DOCKER_REGISTRY-}bancaapi
    hostname: Kafka
    build:
      context: .
      dockerfile: BancaApi/Dockerfile
    restart: always
    
    ports:
       - 127.0.0.1:8002:80
      # - "8082:443"
    # working_dir: /app
    # volumes:
    #   - ./:/app
    # links:
    #    - bancadb
    depends_on:
     - dbsql
     - cache
      
    # networks: 
    #   - mynetwork
    
    environment:
      - MYSQL_HOST= db_banca
      - MYSQL_USER= sa
      - MYSQL_PASSWORD= Password12345
      - MYSQL_DB= Banca
   
     
  cache:
    image: redis:7.2.1
    container_name: redis_image
    # volumes:
    # - .data:/data 
      
    # # network_mode: host
    # environment:
    # # - REDIS_PASSWORD=Password12345
    # # - REDIS_USERNAME=sa
    # - REDIS_PORT=127.0.0.1:6379
    restart: always
    ports:
      - 6379:6379
    # networks: 
    #   - mynetwork
   
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "simpletalk_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dbsql :
    container_name: db_banca
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
   
    environment:
     
     ACCEPT_EULA: Y
     MSSQL_SA_PASSWORD: Password12345
     hostname : db_banca
     MYSQL_DATABASE: Banca
    volumes:
       - dbdata:/var/opt/mssql
      
    ports:
      -  1434:1433
    # networks:
    #    - mynetwork
volumes:
  dbdata:

  